### ISSUE TITLE
The skip_large_bodies flag logic always returns true

### ISSUE THREAD

**Issue by lasrado** [Kong/kong-plugin-liamp#44]
Hi,

The below line of code introduced in 3.5.0 version of this plugin will always have the skip_large_bodies flag as true.

https://github.com/Kong/kong-plugin-aws-lambda/blob/a3e69f92207c867079b5a6f064deb275405dccd5/kong/plugins/aws-lambda/aws-serializer.lua#L57

Since the default is set as true, we would not have an issue when flag is not used. Hence the code could be changed as below?
local skip_large_bodies = config and config.skip_large_bodies

**Comment by Tieske** [comment]
This was fixed in 3.5.1; https://github.com/Kong/kong-plugin-aws-lambda/blob/master/CHANGELOG.md#aws-lambda-351-6-oct-2020

**Comment by lasrado** [comment]
All good. Thanks.

**Comment by djha-skin** [comment]
This is still broken.

https://github.com/Kong/kong-plugin-aws-lambda/blob/a3e69f92207c867079b5a6f064deb275405dccd5/kong/plugins/aws-lambda/aws-serializer.lua#L57

I have been able to confirm experimentally that skip_large_bodies is not honored; it is, in all cases, true. Please fix this, it breaks the plugin.
